### ISSUE TITLE
Bug carrinho de compra passando compras de graça

### ISSUE THREAD

**Issue by iVega123** [iVega123/Aula_4#9]
![__francis_drake_fate_and_1_more_drawn_by_xphlln__sample-652dc858d6c28577d23bdd5df8142a79](https://github.com/iVega123/Aula_4/assets/55510725/e86bc740-9129-4308-b750-aee9fed7c8ca)

https://github.com/iVega123/Aula_4/assets/55510725/ea26acff-8ad8-40f4-a224-6bf39f716970

**Comment by munir155** [comment]
ta roubada demais isso ai

**Comment by glendabianchini** [comment]
![Solène_5-7-2024_72433049](https://github.com/iVega123/Aula_4/assets/88941421/4cbeb2b8-ae27-4b54-98b0-52e33d59ec22)

**Comment by RaphaelSindra** [comment]
mas e a picanha ta de graça tbm?

**Comment by iVega123** [comment]
Resolvido
